on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4                        # Checkout the code. No need of tags and whole history.
        with:
          fetch-depth: 1

      - name: Calculate version
        id: version
        uses: Kantis/semantic-version@master
        with:
          version_format: "${major}.${minor}.${patch}.${increment}-SNAPSHOT"

      -  id: stable-version
         if: steps.version.outputs.is_tagged == 'true'
         run: >
           echo "version=${{ steps.version.outputs.major }}.${{steps.version.outputs.minor }}.${{steps.version.outputs.patch }}" >> $GITHUB_OUTPUT

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build and publish
        run: ./gradlew check publishToMavenLocal -Pversion="${{ steps.stable-version.outputs.version || steps.version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/kantis-ktlint-rules-*.jar